@Library('ostov-library') _

def APP_VERSION = ''
def APP_BUILD = ''
def randomIntInRange(int lowerInt, int upperInt) {
    return Math.abs( new Random().nextInt() % (upperInt - lowerInt) ) + lowerInt
}

pipeline {
    options {
        authorizationMatrix([])
        buildDiscarder logRotator(
            artifactDaysToKeepStr: '',
            artifactNumToKeepStr: '',
            daysToKeepStr: '30',
            numToKeepStr: ''
        )
        skipDefaultCheckout()
        copyArtifactPermission env.JOB_NAME
        ansiColor('xterm')
        timestamps()
    }
    agent none
    stages {

        stage("Build & Test") {
            options {
                timeout(time: 20, unit: 'MINUTES')
            }
            agent { label 'CI' }
            steps {
                checkoutScmGit('https://github.com/ostov/jenkinsfile-delivery-pipeline.git')
                script {
                    env.APP_VERSION = sh (
                        script: 'cat version.properties | grep "APP_VERSION" | awk -F\'[=.]\' \'{print $2 "." $3;}\'',
                        // For Maven use 'xq -r .project.version pom.xml | awk -F\'[.]\' \'{print $1 "." $2;}\''
                        // For Node.js use 'jq -r '.version' package.json | awk -F\'[.]\' \'{print $1 "." $2;}\''
                        returnStdout: true
                    ).trim()
                    env.APP_BUILD = env.BUILD_NUMBER
                    currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}"
                }
                echo "Build & Test"
                sh '''
                    echo "[INFO] Updating version with build number ..."
                    # For Maven use goal "versions:set -DnewVersion=${APP_VERSION}.${APP_BUILD}"
                    # For Node.js use 'sed -i "s/\"version\": \"${APP_VERSION}.*\"/\"version\": \"${APP_VERSION}.${APP_BUILD}\"/g" package.json'
                    echo "[INFO] Starting Build & Test ..."
                    echo "${APP_VERSION}.${BUILD_NUMBER}" > artifact.txt
                    mkdir -p target/test-results/test
                    chmod +x run_tests.sh
                    ./run_tests.sh FooBar
                '''
                sleep randomIntInRange(5,15)
                archiveArtifacts artifacts: 'artifact.txt',
                    allowEmptyArchive: false,
                    fingerprint: true,
                    onlyIfSuccessful: true
            }
            post {
                always {
                    // recordIssues enabledForFailure: true, tools: [mavenConsole(), checkStyle()]
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 1
                }
            }
        }

        // THIS DOES NOT WORK:
        deployStage([ "envName": "DevInt", "timeOut": 10, "lockMilestone": 2, "doneMilestone": 3 ])
    }
}
