def APP_VERSION = ''
def APP_BUILD = ''
def randomIntInRange(int lowerInt, int upperInt) {
    return Math.abs( new Random().nextInt() % (upperInt - lowerInt) ) + lowerInt
}

pipeline {
    options {
        authorizationMatrix([])
        buildDiscarder logRotator(
            artifactDaysToKeepStr: '',
            artifactNumToKeepStr: '',
            daysToKeepStr: '30',
            numToKeepStr: ''
        )
        copyArtifactPermission env.JOB_NAME
        ansiColor('xterm')
        timestamps()
    }
    agent none
    stages {

        stage("Build & Test") {
            options {
                timeout(time: 20, unit: 'MINUTES')
            }
            agent { label 'CI' }
            steps {
                task("Build & Test") {
                    script {
                        env.APP_VERSION = sh (
                            script: 'cat version.properties | grep "APP_VERSION" | awk -F\'[=.]\' \'{print $2 "." $3;}\'',
                            returnStdout: true
                        ).trim()
                        env.APP_BUILD = env.BUILD_NUMBER
                        currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}"
                    }
                    echo "Build & Test"
                    sh '''
                        echo "[INFO] Starting Build & Test ..."
                        echo "${APP_VERSION}.${BUILD_NUMBER}" > artifact.txt
                    '''
                    writeFile file: "target/test-results/test/TEST-FooBar-.xml", text: """
                        <testsuite tests="3">
                            <testcase classname="FooBar-1" name="ASuccessfulTest"/>
                            <testcase classname="FooBar-2" name="AnotherSuccessfulTest"/>
                            <testcase classname="FooBar-3" name="AFailingTest">
                            <failure type="NotEnoughFooBar"> details about failure </failure>
                            </testcase>
                        </testsuite>
                    """
                    sleep randomIntInRange(10,30)
                }
                task("Archive Artifacts") {
                    archiveArtifacts artifacts: 'artifact.txt',
                    allowEmptyArchive: false,
                    fingerprint: true,
                    onlyIfSuccessful: true
                }

            }
            post {
                always {
                    // recordIssues enabledForFailure: true, tools: [mavenConsole(), checkStyle()]
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 1
                }
            }
        }

        stage("Deploy to DevInt") {
            options {
                skipDefaultCheckout()
                timeout(time: 10, unit: 'MINUTES')
            }
            environment {
                envName = "DevInt"
            }
            agent { label env.envName }
            steps {
                lock(resource: env.envName, inversePrecedence: true) {
                    milestone 2
                    script { currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}" }
                    cleanWs()
                    copyArtifacts filter: 'artifact.txt', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                    echo "Deploying ${env.APP_VERSION}.${env.APP_BUILD} to ${env.envName}"
                    sh '''
                        echo "[INFO] Deploying to ${envName} ..."
                        cat artifact.txt
                    '''
                }
                milestone 3
            }
        }

        stage("Tests on DevInt") {
            options {
                skipDefaultCheckout()
                timeout(time: 15, unit: 'MINUTES')
            }
            environment {
                envName = "DevInt"
            }
            agent { label env.envName }
            steps {
                lock(resource: env.envName, inversePrecedence: true) {
                    milestone 4
                    script { currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}" }
                    // checkout changelog: false, scm: [$class: 'GitSCM',
                    //     branches: [[name: "refs/heads/master"]],
                    //     doGenerateSubmoduleConfigurations: false,
                    //     extensions: [[$class: 'WipeWorkspace']],
                    //     submoduleCfg: [],
                    //     userRemoteConfigs: [[
                    //         url: 'git@github.com:Calavista/wifi-indigo.git',
                    //         refspec: '+refs/heads/master:refs/remotes/origin/master',
                    //     ]]
                    // ]
                    echo "Testing on ${env.envName}"
                    sh '''
                        echo "[INFO] Testing ${APP_VERSION}.${APP_BUILD} on ${envName} ..."
                    '''
                    writeFile file: "target/test-results/test/TEST-Foo.xml", text: """
                        <testsuite tests="3">
                            <testcase classname="Foo-1" name="ASuccessfulTest"/>
                            <testcase classname="Foo-2" name="AnotherSuccessfulTest"/>
                            <testcase classname="Foo-3" name="AFailingTest">
                            <failure type="NotEnoughFoo"> details about failure </failure>
                            </testcase>
                        </testsuite>
                    """
                }
            }
            post {
                always {
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 5
                }
            }
        }

        stage("Deploy to QA") {
            options {
                skipDefaultCheckout()
                timeout(time: 10, unit: 'MINUTES')
            }
            input {
                message "Should we continue?"
                ok "Yes, we should"
                submitter "Calavista*Calavista DevOps,marko-bekhta"
            }
            environment {
                envName = "QA"
            }
            agent { label env.envName }
            steps {
                lock(resource: env.envName, inversePrecedence: true) {
                    milestone 6
                    script { currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}" }
                    cleanWs()
                    copyArtifacts filter: 'artifact.txt', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                    echo "Deploying ${env.APP_VERSION}.${env.APP_BUILD} to ${env.envName}"
                    sh '''
                        echo "[INFO] Deploying to ${envName} ..."
                        cat artifact.txt
                    '''
                }
                milestone 7
            }
        }

        stage("Tests on QA") {
            options {
                skipDefaultCheckout()
                timeout(time: 30, unit: 'MINUTES')
            }
            environment {
                envName = "QA"
            }
            agent { label env.envName }
            steps {
                lock(resource: env.envName, inversePrecedence: true) {
                    milestone 8
                    script { currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}" }
                    // checkout changelog: false, scm: [$class: 'GitSCM',
                    //     branches: [[name: "refs/heads/master"]],
                    //     doGenerateSubmoduleConfigurations: false,
                    //     extensions: [[$class: 'WipeWorkspace']],
                    //     submoduleCfg: [],
                    //     userRemoteConfigs: [[
                    //         url: 'git@github.com:Calavista/wifi-indigo.git',
                    //         refspec: '+refs/heads/master:refs/remotes/origin/master',
                    //     ]]
                    // ]
                    echo "Testing on ${env.envName}"
                    sh '''
                        echo "[INFO] Testing ${APP_VERSION}.${APP_BUILD} on ${envName} ..."
                    '''
                    writeFile file: "target/test-results/test/TEST-Bar.xml", text: """
                        <testsuite tests="3">
                            <testcase classname="Bar-1" name="ASuccessfulTest"/>
                            <testcase classname="Bar-2" name="AnotherSuccessfulTest"/>
                            <testcase classname="Bar-3" name="AFailingTest">
                            <failure type="NotEnoughBar"> details about failure </failure>
                            </testcase>
                        </testsuite>
                    """
                }
            }
            post {
                always {
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 9
                }
            }
        }

        stage("Deploy to Staging") {
            options {
                skipDefaultCheckout()
                timeout(time: 14, unit: 'DAYS')
            }
            input {
                message "Should we continue?"
                ok "Yes, we should"
                submitter "Calavista*Calavista DevOps,marko-bekhta"
            }
            environment {
                envName = "Staging"
            }
            agent { label env.envName }
            steps {
                lock(resource: env.envName, inversePrecedence: true) {
                    milestone 10
                    script { currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}" }
                    cleanWs()
                    copyArtifacts filter: 'artifact.txt', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                    echo "Deploying to ${env.envName}"
                    sh '''
                        echo "[INFO] Deploying ${APP_VERSION}.${APP_BUILD} to ${envName} ..."
                        cat artifact.txt
                    '''
                }
                milestone 11
            }
        }

        stage("Deploy to Production") {
            options {
                skipDefaultCheckout()
                timeout(time: 14, unit: 'DAYS')
            }
            input {
                message "Should we continue?"
                ok "Yes, we should"
                submitter "Calavista*Calavista DevOps,marko-bekhta"
            }
            environment {
                envName = "Production"
            }
            agent { label env.envName }
            steps {
                lock(resource: env.envName, inversePrecedence: true) {
                    milestone 12
                    script { currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}" }
                    cleanWs()
                    copyArtifacts filter: 'artifact.txt', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                    echo "Deploying ${env.APP_VERSION}.${env.APP_BUILD} to ${env.envName}"
                    sh '''
                        echo "[INFO] Deploying ${APP_VERSION}.${APP_BUILD} to ${envName} ..."
                        cat artifact.txt
                    '''
                }
            }
        }

    }
}
