@Library('ostov-library') _

/*
library identifier: 'custom-lib@master', retriever: modernSCM([
  $class: 'GitSCMSource',
  remote: 'https://github.com/ostov/jenkinsfile-delivery-pipeline-lib.git'
])
*/

def APP_VERSION = ''
def APP_BUILD = ''
def randomIntInRange(int lowerInt, int upperInt) {
    return Math.abs( new Random().nextInt() % (upperInt - lowerInt) ) + lowerInt
}

pipeline {
    options {
        authorizationMatrix([])
        buildDiscarder logRotator(
            artifactDaysToKeepStr: '',
            artifactNumToKeepStr: '',
            daysToKeepStr: '30',
            numToKeepStr: ''
        )
        copyArtifactPermission env.JOB_NAME
        ansiColor('xterm')
        timestamps()
    }
    agent none
    stages {

        stage("Build & Test") {
            options {
                timeout(time: 20, unit: 'MINUTES')
            }
            agent { label 'CI' }
            steps {
                task("Build & Test") {
                    script {
                        env.APP_VERSION = sh (
                            script: 'echo "1.0"',
                            returnStdout: true
                        ).trim()
                        env.APP_BUILD = env.BUILD_NUMBER
                        currentBuild.displayName = "${env.APP_VERSION}.${env.APP_BUILD}"
                    }
                    echo "Build & Test"
                    sh '''
                        echo "[INFO] Starting Build & Test ..."
                        echo "${APP_VERSION}.${BUILD_NUMBER}" > artifact.txt
                    '''
                    writeFile file: "target/test-results/test/TEST-FooBar.xml", text: """
                        <testsuite tests="3">
                            <testcase classname="FooBar-1" name="ASuccessfulTest"/>
                            <testcase classname="FooBar-2" name="AnotherSuccessfulTest"/>
                            <testcase classname="FooBar-3" name="AFailingTest">
                            <failure type="NotEnoughFooBar"> details about failure </failure>
                            </testcase>
                        </testsuite>
                    """
                    sleep randomIntInRange(5,15)
                }
                task("Archive Artifacts") {
                    archiveArtifacts artifacts: 'artifact.txt',
                    allowEmptyArchive: false,
                    fingerprint: true,
                    onlyIfSuccessful: true
                }

            }
            post {
                always {
                    // recordIssues enabledForFailure: true, tools: [mavenConsole(), checkStyle()]
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 1
                }
            }
        }

        stage("Deploy to DevInt") {
            options {
                skipDefaultCheckout()
                timeout(time: 10, unit: 'MINUTES')
            }
            agent { label env.envName }
            steps {
                deploySteps([ "envName": "DevInt", "lockMilestone": 2, "doneMilestone": 3 ])
            }
        }

        stage("Tests on DevInt") {
            options {
                skipDefaultCheckout()
                timeout(time: 15, unit: 'MINUTES')
            }
            agent { label env.envName }
            steps {
                testSteps([ "envName": "DevInt", "lockMilestone": 4, "testName": "Foo" ])
            }
            post {
                always {
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 5
                }
            }
        }

        stage("Deploy to QA") {
            options {
                skipDefaultCheckout()
                timeout(time: 10, unit: 'MINUTES')
            }
            input {
                message "Should we continue?"
                ok "Yes, we should"
                submitter "ostov"
            }
            agent { label env.envName }
            steps {
                deploySteps([ "envName": "QA", "lockMilestone": 6, "doneMilestone": 7 ])
            }
        }

        stage("Tests on QA") {
            options {
                skipDefaultCheckout()
                timeout(time: 45, unit: 'MINUTES')
            }
            agent { label env.envName }
            steps {
                testSteps([ "envName": "QA", "lockMilestone": 8, "testName": "Bar" ])
            }
            post {
                always {
                    junit skipPublishingChecks: true, testResults: '**/target/test-results/**/TEST*.xml'
                    // jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', execPattern: '**/target/jacoco/**/*.exec', inclusionPattern: '**/*.class', sourceInclusionPattern: '**/*.java'
                    milestone 9
                }
            }
        }

        stage("Deploy to Staging") {
            options {
                skipDefaultCheckout()
                timeout(time: 14, unit: 'DAYS')
            }
            input {
                message "Should we continue?"
                ok "Yes, we should"
                submitter "ostov"
            }
            agent { label env.envName }
            steps {
                deploySteps([ "envName": "Staging", "lockMilestone": 10, "doneMilestone": 11 ])
            }
        }

        stage("Deploy to Production") {
            options {
                skipDefaultCheckout()
                timeout(time: 14, unit: 'DAYS')
            }
            input {
                message "Should we continue?"
                ok "Yes, we should"
                submitter "Calavista*Calavista DevOps,marko-bekhta"
            }
            agent { label env.envName }
            steps {
                deploySteps([ "envName": "Production", "lockMilestone": 12, "doneMilestone": 13 ])
            }
        }

    }
}
